### ISSUE TITLE
On ListsScreen, a nicer way of clicking on a list and redirecting to tobuy list screen

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#10]

**Comment by zznicole** [comment]
it seems like this issue has been addressed. Would you agree?

**Comment by kft-a** [comment]
Not entirely fixed. The clickable area also covers the check item and the delete button, so we always end up in the TobuyListScreen even when trying to delete or check a list.

**Comment by kft-a** [comment]
Fixed by encapsulating title and subtitle in a CardContent tag and using flex grid, nowrap and ellipsis to ensure text is one line and truncated with an ellipsis.

On master, commit #8afe97016.
